# -*- coding: utf-8 -*-
# *_data_path 是解压好的LUNA16数据文件夹
config = {'train_data_path':['/home/RAID1/DataSet/LUNA16/subset0/',
                             '/home/RAID1/DataSet/LUNA16/subset1/',
                             '/home/RAID1/DataSet/LUNA16/subset2/',
                             '/home/RAID1/DataSet/LUNA16/subset3/',
                             '/home/RAID1/DataSet/LUNA16/subset4/',
                             '/home/RAID1/DataSet/LUNA16/subset5/',
                             '/home/RAID1/DataSet/LUNA16/subset6/',
                             '/home/RAID1/DataSet/LUNA16/subset7/',
                             '/home/RAID1/DataSet/LUNA16/subset8/'],
          'val_data_path':  ['/home/RAID1/DataSet/LUNA16/subset9/'],
          'test_data_path': ['/home/RAID1/DataSet/LUNA16/subset9/'],
          # *_preprocess_result_path 是预处理产生的数据的存储位置  
          'train_preprocess_result_path':'/home/RAID1/DataSet/LUNA16/train_preprocess/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'/home/RAID1/DataSet/LUNA16/val_preprocess/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'/home/RAID1/DataSet/LUNA16/test_preprocess/',
          # *_annos_path 是LUNA16标注文件所在的位置 
          'train_annos_path':'/home/RAID1/DataSet/LUNA16/CSVFILES/annotations.csv',
          'val_annos_path':'/home/RAID1/DataSet/LUNA16/CSVFILES/annotations.csv',
          'test_annos_path':'/home/RAID1/DataSet/LUNA16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',
          # *_segment 是luna16的分割数据,数据集自带
          'luna_segment':'/home/RAID1/DataSet/LUNA16/seg-lungs-LUNA16/', # download from https://luna16.grand-challenge.org/data/
          'preprocess_result_path':'/home/RAID1/DataSet/LUNA16/preprocess_result',
          'luna_data':'/home/RAID1/DataSet/LUNA16/',
          'luna_label':'/home/RAID1/DataSet/LUNA16/CSVFILES/annotations.csv'
         } 